### ISSUE TITLE
mermaid only render "odd" markdown blocks

### ISSUE THREAD

**Issue by kienct89** [zzossig/hugo-theme-zzo#13] opened 2019-11-26 02:14 UTC
Hi zzossig,

according to this code, mermaid only renders "odd" markdown blocks
I notice your comment as below

> // mermaid Fix Mermaid.js clash with Highlight.js.  

https://github.com/zzossig/hugo-theme-zzo/blob/be7dc0192d1250d90af0788d8d8eee78c0d4e9d8/layouts/partials/script/single-script.html#L438

**Comment by zzossig** [comment] 2019-11-26 02:19
Mermaid Library is not rendering on your end?? The "odd" is because I didn't want to show line numbers on code block.
![bc](https://user-images.githubusercontent.com/52706977/69594100-9b6f4980-103e-11ea-9ab7-8d9f1f6cf8c6.png)

**Comment by kienct89** [comment] 2019-11-26 02:24
I tested with 8 mermaid markdown blocks

it only renders first 2nd, 4th, 6th and so on

**Comment by zzossig** [comment] 2019-11-26 02:26
ah I see. It should be fixed. Thanks for reporting the bug

**Comment by zzossig** [comment] 2019-11-26 03:51
I can't reproduce this. Are you tested this on Mac OS? Can you give me the mermaid code?

**Comment by kienct89** [comment] 2019-11-26 03:57
I'm using exact same content to test as `test_mermaid.md`

```

```mermaid
graph TD;
  A-->B;
  A-->C;
  B-->D;
  C-->D;
```

```mermaid
sequenceDiagram
  participant Alice
  participant Bob
  Alice->John: Hello John, how are you?
  loop Healthcheck
      John->John: Fight against hypochondria
  end
  Note right of John: Rational thoughts <br/>prevail...
  John-->Alice: Great!
  John->Bob: How about you?
  Bob-->John: Jolly good!
```

```mermaid
graph TD
A[Hard] -->|Text| B(Round)
B --> C{Decision}
C -->|One| D[Result 1]
C -->|Two| E[Result 2]
```

```mermaid
gantt
section Section
Completed :done,    des1, 2014-01-06,2014-01-08
Active        :active,  des2, 2014-01-07, 3d
Parallel 1   :         des3, after des1, 1d
Parallel 2   :         des4, after des1, 1d
Parallel 3   :         des5, after des3, 1d
Parallel 4   :         des6, after des4, 1d
```

```mermaid
classDiagram
Class01 <|-- AveryLongClass : Cool
<<interface>> Class01
Class09 --> C2 : Where am i?
Class09 --* C3
Class09 --|> Class07
Class07 : equals()
Class07 : Object[] elementData
Class01 : size()
Class01 : int chimp
Class01 : int gorilla
class Class10 {
  <<service>>
  int id
  size()
}
```

```mermaid
stateDiagram
[*] --> Still
Still --> [*]
Still --> Moving
Moving --> Still
Moving --> Crash
Crash --> [*]
```

```mermaid
pie
"Dogs" : 386
"Cats" : 85
"Rats" : 15 
```
```

**Comment by zzossig** [comment] 2019-11-26 05:58
@kienct89 Hey~ One more thing I wanna check. Did you set 
```bash
...
pygmentsOptions = "linenos=table"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true
...
```
at config.toml file?

**Comment by zzossig** [comment] 2019-11-28 03:31
@kienct89 Can you update theme and check it again? I made some changes. If it's not working, update hugo version. If you are using Chocolatey for package management, open a powerShell as an administrator and type this and then run hugo again.
```shell
choco install hugo-extended
```

**Comment by zzossig** [comment] 2019-12-05 14:10
@kienct89 There have been many changes in this project after Hugo v.0.60.0 released. I'm pretty sure that this issue fixed now. So I'm going to close this issue. If it's not, feel free to re-open this issue😋

**Closed** 2019-12-05 14:10 UTC
Labels: bug
