### ISSUE TITLE
Top posts in sidebar

### ISSUE THREAD

**Issue by szpak** [zzossig/hugo-theme-zzo#184] opened 2020-02-18 15:38 UTC
Another idea (lurked in WordPress) came to my mind. A list of "top posts".

I could be a separate (optional, probably disabled by default) section in the sidebar, displayed probably between Posts and Tags. It would be powered by the weight mechanism added to particular posts (added and updated occasionally by hand, based on number of hits or whatever else) . While the same weight value (or lack of) for 2 or more posts they should be sorted by date descending.
It would be required to change the "Posts" header to "Recent Posts" and to add "Top Posts" (probably using `Title` from `_index.md` for the "Posts" name).

WDYT?

**Comment by zzossig** [comment] 2020-02-18 15:52
It can be easily implemented using weight
```yaml
---
title:
...
weight: 1
---
```

If you need this feature, add it.

>It would be required to change the "Posts" header to "Recent Posts" and to add "Top Posts"

Yes, It should be changed manually

**Comment by szpak** [comment] 2020-02-18 15:57
I would like to have it in my blog, so if it is not problematic to implement I will be happy to see it in Zzo :).

It should be rather disabled by default to do not confuse existing users of your theme.

**Comment by zzossig** [comment] 2020-02-18 15:58
It can be done with `.ByWeight` keyword thanks for the Hugo
I'll commit code after I fixed another issue.

**Comment by zzossig** [comment] 2020-02-18 16:30
I committed the code!
You can set `weight` front-matter.
You should set it `1` or above

**Comment by zzossig** [comment] 2020-02-18 16:45
Oops, I misunderstood.
You mean display top post in the sidebar.
I’ll do it tomarrow.
I’m going to sleep now

**Comment by szpak** [comment] 2020-02-18 17:20
Yes, another lists in the sidebar :).

Sleep well ;-)

**Comment by zzossig** [comment] 2020-02-19 01:34
I added another list in the sidebar.
Follow the below steps.

1. In your `params.toml` file,
```toml
...
enableSidebarPostsByOrder = true
```

2. Add a new i18n item to your i18n file. e.g: `root/i18n/en.toml`
```toml
...
[posts-by-order]
other = "MY TOP POSTS"
```

3. Add new front-matter `order` to your post md file.
```yaml
---
title: 
...
order: 1
---
```

**Comment by szpak** [comment] 2020-02-19 11:39
I've just tested it and it works great, thanks!

Two small suggestions:
1. Maybe it would be good to add `[posts-by-order]` entry to the `*.toml` provided in your theme by default (to have it localized by default once enabled)?
2. Having no pages in `order` found it the list header could be omitted (the same as for series, tags, ...).

**Comment by szpak** [comment] 2020-02-19 11:44
Btw, having commits related to some GitHub issue you could put `[#184]` somewhere in the commit message. Thanks to that, it will be referenced in that issue (and there will be a link from the commit to it). It would be useful to people trying to get more information about the implementation of a given feature/bug fix.

**Comment by zzossig** [comment] 2020-02-19 11:45
I was tried to do that.
But it closes the issue automatically

**Comment by szpak** [comment] 2020-02-19 11:52
Maybe you wrote `fixes #XX`. Just `#XX` shouldn't close it. I propose to try it again - maybe it was a bug then.

**Comment by zzossig** [comment] 2020-02-19 11:52
I'll try again here

**Closed** 2020-02-19 12:09 UTC

**Comment by zzossig** [comment] 2020-02-19 12:11
`#xx` close issue automatically.
Maybe it's a bug or intended behavior.

Anyway, I did your suggestions https://github.com/zzossig/hugo-theme-zzo/issues/184#issuecomment-588179493

**Comment by szpak** [comment] 2020-02-19 12:22
It is intended. You requested to close it:
![image](https://user-images.githubusercontent.com/148013/74833877-a45c7800-531a-11ea-9677-68d26f244e83.png)

See [here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for the supported keywords

if you don't want to close it just put `#184` and there will be a reference.

**Comment by zzossig** [comment] 2020-02-19 12:24
It's good information! Thanks

**Comment by zeptobook** [comment] 2020-06-18 01:15
You made my life easier by fixing this.
