### ISSUE TITLE
Make sidebar show in single post

### ISSUE THREAD

**Issue by djiwan** [zzossig/hugo-theme-zzo#264] opened 2020-04-26 18:06 UTC
I think it will really helpfull when i read post, and want to navigate to all categories or tags.

if sidebar enable in single post, ToC will place "outer" by default,, 
and for the search result it will using "side" by default, or you can use the searchmobile 

and i think, sidebar dont need recent posts, they already shown in home and posts page,, put random posts instead, it will promote other/old posts,,

**Comment by szpak** [comment] 2020-05-10 22:42
Duplicate of #221. You can make your comment there.

**Closed** 2020-05-15 13:49 UTC
