### ISSUE TITLE
Problem with Search

### ISSUE THREAD

**Issue by onesentforth** [zzossig/hugo-theme-zzo#44] opened 2019-12-28 03:02 UTC
Whenever using the "Search" feature, clicking an item in the list does not send the browser to that page. But if you use the arrows to select an item and press "Enter," it will send the browser to the highlighted item.

**Comment by zzossig** [comment] 2019-12-28 03:05
What browser are you using?

**Comment by onesentforth** [comment] 2019-12-28 03:07
Brave browser.
I'm exploring your Demo on the Hugo Themes website.
I really like the theme! Looks nice

**Comment by onesentforth** [comment] 2019-12-28 03:09
Just tried it in Microsoft Edge. Same issue.

**Comment by zzossig** [comment] 2019-12-28 03:13
Thx!
I can't reproduce it. I tested on edge but works as expected.
Are you testing it on local? or just an example site?

**Comment by onesentforth** [comment] 2019-12-28 03:16
Just on the [example site](https://themes.gohugo.io//theme/hugo-theme-zzo/en/)

I haven't tested it locally or deployed it yet.

**Comment by zzossig** [comment] 2019-12-28 03:16
Can you check it on my blog?
https://zzossig.io/

**Comment by onesentforth** [comment] 2019-12-28 03:19
Does the same thing there. Clicking an item returned in the search results does nothing, but highlighting an item with the arrows and pressing "enter" works fine.

**Comment by onesentforth** [comment] 2019-12-28 03:23
I just tried it on another laptop running linux, and it worked.
The laptop that I originally tried runs on Windows 10.

**Comment by onesentforth** [comment] 2019-12-28 03:29
I found that on my Windows laptop, if I rapidly double-click on an item returned in the search bar, it works perfectly.

It's a brand new laptop, so I don't know why a single-click won't perform the same action.

It must be an issue with my system.
Thank you for your rapid response!

**Comment by zzossig** [comment] 2019-12-28 03:33
Hmm, I also tested it on Windows 10 and macOS, but I can't reproduce it on my end.
When you hover your mouse on the list, you can see the bottom left side text on the browser. It means the list item has a link. 
![34](https://user-images.githubusercontent.com/52706977/71538400-86534680-296d-11ea-8cf1-30e8a5a6d05c.png)

Oh ok, I also think it's related to the system. If it's not, feel free to reopen this issue.
I'm closing this issue at this moment

**Closed by zzossig** 2019-12-28 03:33 UTC
