### ISSUE TITLE
fail to execute example site

### ISSUE THREAD

**Issue by CapMocha** [zzossig/hugo-theme-zzo#1] opened 2019-11-12 11:12 UTC
when I execute the command "hugo server --themesDir ..\.." in the command line,  the following error occurs, and I don't know how to solve it.
![image](https://user-images.githubusercontent.com/57527488/68667034-079e7780-0580-11ea-9cea-7b7481d12321.png)

**Comment by fandean** [comment] 2019-11-12 11:42
Delete 'rich-content.md'. It should be a network problem.  
`api.instagram.com` is not accessible in some countries, such as China.


删除 `rich-content.md` 就可以了，应该是网络问题。https://api.instagram.com 在某些国家无法访问，比如中国。。

**Comment by zzossig** [comment] 2019-11-12 13:33
There are 2 error in the screen shot. One is instgram api call error and the other is mmark: failed. The mmark error will be fixed soon and since mmark error not gonna make a infinite loop, I suspect your api call may be the problem. As @fandean mentioned, It may be a network problem I think.

**Comment by CapMocha** [comment] 2019-11-12 17:57
@fandean I delete the rich-content.md, and the exampleSite could work, but when I execute in the root of web, the following error occurs
![image](https://user-images.githubusercontent.com/57527488/68697004-f45bce00-05b8-11ea-8587-27c06796aba1.png)

**Comment by zzossig** [comment] 2019-11-12 22:13
@CapMocha Ah Ok this error is caused by missing configuration params. This project is in very early stage and I’m actively update this repo. So this happened. I added couple of params to config/_default/params.toml so can you check the readme? Once you add missing params, that should work

**Comment by CapMocha** [comment] 2019-11-13 07:19
@zzossig 
I just do as the Readme.md to create the config folder in the root path, and create the _default folder in the config folder, and then create four separate config file just like the Readme.md, but the error still occur.
When I copy the config.toml in the the root/themes/zzo/exampleSite to the root/ and delete the root/config folder, it works, so I  want to know if I want to set the multi language, I should write config in the root/config/_default folder, I want konw does this make an effect, does the root/config folder will shllow the root/config.toml in my case.

**Comment by zzossig** [comment] 2019-11-13 07:35
It doen't matter if you have just one config file that contains all configurations. It's matter of preference. If that is works, then it's fine. But I prefer to separate config files. You can use root/config.toml

**Closed** 2019-11-18 19:19 UTC
